neuralnet:
  input:
    - 4

  hiddenLayers:
    - size:
        - 4
        - 2
      activation_function: tanh
      weight_regularization: glorot
    - size:
        - 2
        - 2
      activation_function: tanh
      weight_regularization: glorot
  output:
    size:
      - 1
    weight_regularization: glorot
    activation_function: softmax

