/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package IT3030.DeepLearning

import IT3030.DeepLearning.Config.ConfigParser

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
    val config = ConfigParser("config.yml")
}

fun main() {
    println(App().greeting)
}
