/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.0/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.4.31"

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    kotlin("plugin.serialization") version "1.5.0"
}

repositories {
    // add Spek 2 development repository
    maven { url = uri("https://dl.bintray.com/spekframework/spek-dev") }
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.0-jre")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.1")
    implementation("com.charleskorn.kaml:kaml:0.34.0")

    // Testing
    testImplementation("org.spekframework.spek2:spek-dsl-jvm:2.0.16")
    testRuntimeOnly("org.spekframework.spek2:spek-runner-junit5:2.0.15")

    // spek requires kotlin-reflect, can be omitted if already in the classpath
    testRuntimeOnly("org.jetbrains.kotlin:kotlin-reflect:1.4.31")

    // include JUnit 5 assertions
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.2.0")

    // https://mvnrepository.com/artifact/com.charleskorn.kaml/kaml
    runtimeOnly(group= "com.charleskorn.kaml", name= "kaml", version= "0.34.0")
}

// setup the test task

application {
    // Define the main class for the application.
    mainClass.set("IT3030.DeepLearning.AppKt")
}

tasks.test {
    useJUnitPlatform {
        includeEngines("spek2")
    }
}
